#!/bin/bash
#########################################################
# @author: <juliolimareis@gmail.com>                    #
# @description: Script para levantar a aplicação.       #               					# 
#########################################################
# =========================================
#             * Requisitos * 
# Sistema Ubuntu 20.04
# Programas: NPM, Docker e docker-compose
# =========================================

function refresh(){
	npm run build
	sudo docker-compose up --force-recreate -d 
	cp ./.htaccess ./dist
}

case $1 in
"-i"|"install") 
	#install docker
	sudo apt-get update

	sudo apt-get install \
			apt-transport-https \
			ca-certificates \
			curl \
			gnupg-agent \
			software-properties-common

	curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

	sudo apt-key fingerprint 0EBFCD88

	sudo add-apt-repository \
		"deb [arch=amd64] https://download.docker.com/linux/ubuntu \
		$(lsb_release -cs) \
		stable"

	sudo apt-get update

	sudo apt-get install docker-ce docker-ce-cli containerd.io

	sudo curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

	sudo chmod +x /usr/local/bin/docker-compose

	# install npm
	sudo apt install npm

	npm install 
;; 
*) 
	refresh
;;
esac




